In [40]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from model_from_scratch import MultiLayerPercepTron

In [41]:
df_raw = pd.read_csv('data/raw/housing.csv')

In [42]:
df_raw.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [43]:
df_raw.info()
df_raw.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [44]:
print(list(df_raw.columns))
print(len(list(df_raw.columns)))

['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value', 'ocean_proximity']
10

In [45]:
df_raw.duplicated().sum()

np.int64(0)

In [46]:
df_raw.isna().sum().sum()

np.int64(207)

In [47]:
df_cleaned = df_raw.dropna()

In [48]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

X = df_cleaned.drop(columns=['median_house_value', 'ocean_proximity']).values
y = df_cleaned['median_house_value'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler_X = StandardScaler()
X_train_scaled = scaler_X.fit_transform(X_train)
X_test_scaled = scaler_X.transform(X_test)

scaler_y = StandardScaler()
y_train_scaled = scaler_y.fit_transform(y_train.reshape(-1, 1))
y_test_scaled = scaler_y.transform(y_test.reshape(-1, 1))

mlp = MultiLayerPercepTron(input_dim=8, epochs=500, lr=0.1)
mlp.fit(X_train_scaled, y_train_scaled)

Epoch 0/500 - Loss: 1.0000
Epoch 10/500 - Loss: 1.0000
Epoch 20/500 - Loss: 0.9999
Epoch 30/500 - Loss: 0.9999
Epoch 40/500 - Loss: 0.9999
Epoch 50/500 - Loss: 0.9999
Epoch 60/500 - Loss: 0.9998
Epoch 70/500 - Loss: 0.9998
Epoch 80/500 - Loss: 0.9997
Epoch 90/500 - Loss: 0.9996
Epoch 100/500 - Loss: 0.9995
Epoch 110/500 - Loss: 0.9994
Epoch 120/500 - Loss: 0.9992
Epoch 130/500 - Loss: 0.9989
Epoch 140/500 - Loss: 0.9984
Epoch 150/500 - Loss: 0.9977
Epoch 160/500 - Loss: 0.9966
Epoch 170/500 - Loss: 0.9947
Epoch 180/500 - Loss: 0.9911
Epoch 190/500 - Loss: 0.9836
Epoch 200/500 - Loss: 0.9657
Epoch 210/500 - Loss: 0.9142
Epoch 220/500 - Loss: 0.7454
Epoch 230/500 - Loss: 0.4937
Epoch 240/500 - Loss: 0.4278
Epoch 250/500 - Loss: 0.4009
Epoch 260/500 - Loss: 0.3796
Epoch 270/500 - Loss: 0.3621
Epoch 280/500 - Loss: 0.3486
Epoch 290/500 - Loss: 0.3385
Epoch 300/500 - Loss: 0.3312
Epoch 310/500 - Loss: 0.3256
Epoch 320/500 - Loss: 0.3214
Epoch 330/500 - Loss: 0.3179
Epoch 340/500 - Loss: 0.3150
Epoch 350/500 - Loss: 0.3126
Epoch 360/500 - Loss: 0.3104
Epoch 370/500 - Loss: 0.3084
Epoch 380/500 - Loss: 0.3065
Epoch 390/500 - Loss: 0.3048
Epoch 400/500 - Loss: 0.3031
Epoch 410/500 - Loss: 0.3014
Epoch 420/500 - Loss: 0.2999
Epoch 430/500 - Loss: 0.2983
Epoch 440/500 - Loss: 0.2967
Epoch 450/500 - Loss: 0.2951
Epoch 460/500 - Loss: 0.2935
Epoch 470/500 - Loss: 0.2920
Epoch 480/500 - Loss: 0.2905
Epoch 490/500 - Loss: 0.2890