In [100]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from model_from_scratch import MultiLayerPercepTron

In [101]:
df_raw = pd.read_csv('data/raw/housing.csv')

In [102]:
df_raw.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [103]:
df_raw.info()
df_raw.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [104]:
print(list(df_raw.columns))
print(len(list(df_raw.columns)))

['longitude', 'latitude', 'housing_median_age', 'total_rooms', 'total_bedrooms', 'population', 'households', 'median_income', 'median_house_value', 'ocean_proximity']
10

In [105]:
df_raw.duplicated().sum()

np.int64(0)

In [106]:
df_raw.isna().sum().sum()

np.int64(207)

In [107]:
df_cleaned = df_raw.dropna()

In [108]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import numpy as np

X = df_cleaned.drop(columns=['median_house_value', 'ocean_proximity']).values
y = df_cleaned['median_house_value'].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler_X = StandardScaler()
X_train_scaled = scaler_X.fit_transform(X_train)
X_test_scaled = scaler_X.transform(X_test)

scaler_y = StandardScaler()
y_train_scaled = scaler_y.fit_transform(y_train.reshape(-1, 1))
y_test_scaled = scaler_y.transform(y_test.reshape(-1, 1))

mlp = MultiLayerPercepTron(input_dim=8, epochs=5000, lr=0.1)
mlp.fit(X_train_scaled, y_train_scaled)

Epoch 0/5000 - Loss: 1.0000
Epoch 10/5000 - Loss: 1.0000
Epoch 20/5000 - Loss: 1.0000
Epoch 30/5000 - Loss: 0.9999
Epoch 40/5000 - Loss: 0.9999
Epoch 50/5000 - Loss: 0.9999
Epoch 60/5000 - Loss: 0.9998
Epoch 70/5000 - Loss: 0.9998
Epoch 80/5000 - Loss: 0.9997
Epoch 90/5000 - Loss: 0.9997
Epoch 100/5000 - Loss: 0.9996
Epoch 110/5000 - Loss: 0.9994
Epoch 120/5000 - Loss: 0.9992
Epoch 130/5000 - Loss: 0.9989
Epoch 140/5000 - Loss: 0.9984
Epoch 150/5000 - Loss: 0.9977
Epoch 160/5000 - Loss: 0.9966
Epoch 170/5000 - Loss: 0.9946
Epoch 180/5000 - Loss: 0.9907
Epoch 190/5000 - Loss: 0.9823
Epoch 200/5000 - Loss: 0.9611
Epoch 210/5000 - Loss: 0.8955
Epoch 220/5000 - Loss: 0.6851
Epoch 230/5000 - Loss: 0.4759
Epoch 240/5000 - Loss: 0.4269
Epoch 250/5000 - Loss: 0.4009
Epoch 260/5000 - Loss: 0.3797
Epoch 270/5000 - Loss: 0.3623
Epoch 280/5000 - Loss: 0.3489
Epoch 290/5000 - Loss: 0.3390
Epoch 300/5000 - Loss: 0.3316
Epoch 310/5000 - Loss: 0.3260
Epoch 320/5000 - Loss: 0.3219
Epoch 330/5000 - Loss: 0.3186
Epoch 340/5000 - Loss: 0.3159
Epoch 350/5000 - Loss: 0.3136
Epoch 360/5000 - Loss: 0.3114
Epoch 370/5000 - Loss: 0.3095
Epoch 380/5000 - Loss: 0.3076
Epoch 390/5000 - Loss: 0.3058
Epoch 400/5000 - Loss: 0.3042
Epoch 410/5000 - Loss: 0.3025
Epoch 420/5000 - Loss: 0.3010
Epoch 430/5000 - Loss: 0.2995
Epoch 440/5000 - Loss: 0.2980
Epoch 450/5000 - Loss: 0.2966
Epoch 460/5000 - Loss: 0.2951
Epoch 470/5000 - Loss: 0.2937
Epoch 480/5000 - Loss: 0.2924
Epoch 490/5000 - Loss: 0.2910
Epoch 500/5000 - Loss: 0.2897
Epoch 510/5000 - Loss: 0.2884
Epoch 520/5000 - Loss: 0.2871
Epoch 530/5000 - Loss: 0.2858
Epoch 540/5000 - Loss: 0.2846
Epoch 550/5000 - Loss: 0.2834
Epoch 560/5000 - Loss: 0.2822
Epoch 570/5000 - Loss: 0.2811
Epoch 580/5000 - Loss: 0.2800
Epoch 590/5000 - Loss: 0.2790
Epoch 600/5000 - Loss: 0.2780
Epoch 610/5000 - Loss: 0.2771
Epoch 620/5000 - Loss: 0.2762
Epoch 630/5000 - Loss: 0.2754
Epoch 640/5000 - Loss: 0.2747
Epoch 650/5000 - Loss: 0.2739
Epoch 660/5000 - Loss: 0.2733
Epoch 670/5000 - Loss: 0.2726
Epoch 680/5000 - Loss: 0.2720
Epoch 690/5000 - Loss: 0.2714
Epoch 700/5000 - Loss: 0.2710
Epoch 710/5000 - Loss: 0.2720
Epoch 720/5000 - Loss: 0.2895
Epoch 730/5000 - Loss: 0.3209
Epoch 740/5000 - Loss: 0.2829
Epoch 750/5000 - Loss: 0.2738
Epoch 760/5000 - Loss: 0.2724
Epoch 770/5000 - Loss: 0.2739
Epoch 780/5000 - Loss: 0.2797
Epoch 790/5000 - Loss: 0.2874
Epoch 800/5000 - Loss: 0.2850
Epoch 810/5000 - Loss: 0.2784
Epoch 820/5000 - Loss: 0.2754
Epoch 830/5000 - Loss: 0.2753
Epoch 840/5000 - Loss: 0.2769
Epoch 850/5000 - Loss: 0.2793
Epoch 860/5000 - Loss: 0.2799
Epoch 870/5000 - Loss: 0.2780
Epoch 880/5000 - Loss: 0.2764
Epoch 890/5000 - Loss: 0.2757
Epoch 900/5000 - Loss: 0.2758
Epoch 910/5000 - Loss: 0.2763
Epoch 920/5000 - Loss: 0.2767
Epoch 930/5000 - Loss: 0.2763
Epoch 940/5000 - Loss: 0.2756
Epoch 950/5000 - Loss: 0.2749
Epoch 960/5000 - Loss: 0.2746
Epoch 970/5000 - Loss: 0.2747
Epoch 980/5000 - Loss: 0.2749
Epoch 990/5000 - Loss: 0.2748
Epoch 1000/5000 - Loss: 0.2745
Epoch 1010/5000 - Loss: 0.2742
Epoch 1020/5000 - Loss: 0.2736
Epoch 1030/5000 - Loss: 0.2731
Epoch 1040/5000 - Loss: 0.2729
Epoch 1050/5000 - Loss: 0.2728
Epoch 1060/5000 - Loss: 0.2729
Epoch 1070/5000 - Loss: 0.2727
Epoch 1080/5000 - Loss: 0.2721
Epoch 1090/5000 - Loss: 0.2715
Epoch 1100/5000 - Loss: 0.2713
Epoch 1110/5000 - Loss: 0.2713
Epoch 1120/5000 - Loss: 0.2714
Epoch 1130/5000 - Loss: 0.2713
Epoch 1140/5000 - Loss: 0.2711
Epoch 1150/5000 - Loss: 0.2709
Epoch 1160/5000 - Loss: 0.2708
Epoch 1170/5000 - Loss: 0.2706
Epoch 1180/5000 - Loss: 0.2703
Epoch 1190/5000 - Loss: 0.2699
Epoch 1200/5000 - Loss: 0.2697
Epoch 1210/5000 - Loss: 0.2695
Epoch 1220/5000 - Loss: 0.2695
Epoch 1230/5000 - Loss: 0.2696
Epoch 1240/5000 - Loss: 0.2695
Epoch 1250/5000 - Loss: 0.2693
Epoch 1260/5000 - Loss: 0.2690
Epoch 1270/5000 - Loss: 0.2685
Epoch 1280/5000 - Loss: 0.2680
Epoch 1290/5000 - Loss: 0.2678
Epoch 1300/5000 - Loss: 0.2676
Epoch 1310/5000 - Loss: 0.2672
Epoch 1320/5000 - Loss: 0.2669
Epoch 1330/5000 - Loss: 0.2668
Epoch 1340/5000 - Loss: 0.2667
Epoch 1350/5000 - Loss: 0.2667
Epoch 1360/5000 - Loss: 0.2665
Epoch 1370/5000 - Loss: 0.2661
Epoch 1380/5000 - Loss: 0.2658
Epoch 1390/5000 - Loss: 0.2658
Epoch 1400/5000 - Loss: 0.2658
Epoch 1410/5000 - Loss: 0.2657
Epoch 1420/5000 - Loss: 0.2654
Epoch 1430/5000 - Loss: 0.2651
Epoch 1440/5000 - Loss: 0.2648
Epoch 1450/5000 - Loss: 0.2645
Epoch 1460/5000 - Loss: 0.2644
Epoch 1470/5000 - Loss: 0.2644
Epoch 1480/5000 - Loss: 0.2642
Epoch 1490/5000 - Loss: 0.2640
Epoch 1500/5000 - Loss: 0.2640
Epoch 1510/5000 - Loss: 0.2640
Epoch 1520/5000 - Loss: 0.2636
Epoch 1530/5000 - Loss: 0.2632
Epoch 1540/5000 - Loss: 0.2631
Epoch 1550/5000 - Loss: 0.2630
Epoch 1560/5000 - Loss: 0.2628
Epoch 1570/5000 - Loss: 0.2628
Epoch 1580/5000 - Loss: 0.2628
Epoch 1590/5000 - Loss: 0.2627
Epoch 1600/5000 - Loss: 0.2627
Epoch 1610/5000 - Loss: 0.2625
Epoch 1620/5000 - Loss: 0.2625
Epoch 1630/5000 - Loss: 0.2623
Epoch 1640/5000 - Loss: 0.2622
Epoch 1650/5000 - Loss: 0.2619
Epoch 1660/5000 - Loss: 0.2615
Epoch 1670/5000 - Loss: 0.2612
Epoch 1680/5000 - Loss: 0.2611
Epoch 1690/5000 - Loss: 0.2611
Epoch 1700/5000 - Loss: 0.2611
Epoch 1710/5000 - Loss: 0.2608
Epoch 1720/5000 - Loss: 0.2605
Epoch 1730/5000 - Loss: 0.2603
Epoch 1740/5000 - Loss: 0.2602
Epoch 1750/5000 - Loss: 0.2602
Epoch 1760/5000 - Loss: 0.2600
Epoch 1770/5000 - Loss: 0.2598
Epoch 1780/5000 - Loss: 0.2595
Epoch 1790/5000 - Loss: 0.2593
Epoch 1800/5000 - Loss: 0.2590
Epoch 1810/5000 - Loss: 0.2588
Epoch 1820/5000 - Loss: 0.2587
Epoch 1830/5000 - Loss: 0.2586
Epoch 1840/5000 - Loss: 0.2587
Epoch 1850/5000 - Loss: 0.2586
Epoch 1860/5000 - Loss: 0.2584
Epoch 1870/5000 - Loss: 0.2582
Epoch 1880/5000 - Loss: 0.2580
Epoch 1890/5000 - Loss: 0.2579
Epoch 1900/5000 - Loss: 0.2578
Epoch 1910/5000 - Loss: 0.2576
Epoch 1920/5000 - Loss: 0.2573
Epoch 1930/5000 - Loss: 0.2572
Epoch 1940/5000 - Loss: 0.2572
Epoch 1950/5000 - Loss: 0.2570
Epoch 1960/5000 - Loss: 0.2569
Epoch 1970/5000 - Loss: 0.2566
Epoch 1980/5000 - Loss: 0.2563
Epoch 1990/5000 - Loss: 0.2562
Epoch 2000/5000 - Loss: 0.2561
Epoch 2010/5000 - Loss: 0.2557
Epoch 2020/5000 - Loss: 0.2554
Epoch 2030/5000 - Loss: 0.2551
Epoch 2040/5000 - Loss: 0.2549
Epoch 2050/5000 - Loss: 0.2549
Epoch 2060/5000 - Loss: 0.2551
Epoch 2070/5000 - Loss: 0.2551
Epoch 2080/5000 - Loss: 0.2548
Epoch 2090/5000 - Loss: 0.2544
Epoch 2100/5000 - Loss: 0.2545
Epoch 2110/5000 - Loss: 0.2546
Epoch 2120/5000 - Loss: 0.2543
Epoch 2130/5000 - Loss: 0.2539
Epoch 2140/5000 - Loss: 0.2535
Epoch 2150/5000 - Loss: 0.2535
Epoch 2160/5000 - Loss: 0.2536
Epoch 2170/5000 - Loss: 0.2533
Epoch 2180/5000 - Loss: 0.2531
Epoch 2190/5000 - Loss: 0.2529
Epoch 2200/5000 - Loss: 0.2526
Epoch 2210/5000 - Loss: 0.2524
Epoch 2220/5000 - Loss: 0.2523
Epoch 2230/5000 - Loss: 0.2522
Epoch 2240/5000 - Loss: 0.2520
Epoch 2250/5000 - Loss: 0.2515
Epoch 2260/5000 - Loss: 0.2512
Epoch 2270/5000 - Loss: 0.2511
Epoch 2280/5000 - Loss: 0.2512
Epoch 2290/5000 - Loss: 0.2511
Epoch 2300/5000 - Loss: 0.2509
Epoch 2310/5000 - Loss: 0.2506
Epoch 2320/5000 - Loss: 0.2506
Epoch 2330/5000 - Loss: 0.2503
Epoch 2340/5000 - Loss: 0.2501
Epoch 2350/5000 - Loss: 0.2502
Epoch 2360/5000 - Loss: 0.2500
Epoch 2370/5000 - Loss: 0.2497
Epoch 2380/5000 - Loss: 0.2496
Epoch 2390/5000 - Loss: 0.2496
Epoch 2400/5000 - Loss: 0.2496
Epoch 2410/5000 - Loss: 0.2490
Epoch 2420/5000 - Loss: 0.2484
Epoch 2430/5000 - Loss: 0.2484
Epoch 2440/5000 - Loss: 0.2486
Epoch 2450/5000 - Loss: 0.2487
Epoch 2460/5000 - Loss: 0.2486
Epoch 2470/5000 - Loss: 0.2483
Epoch 2480/5000 - Loss: 0.2480
Epoch 2490/5000 - Loss: 0.2479
Epoch 2500/5000 - Loss: 0.2480
Epoch 2510/5000 - Loss: 0.2480
Epoch 2520/5000 - Loss: 0.2476
Epoch 2530/5000 - Loss: 0.2471
Epoch 2540/5000 - Loss: 0.2469
Epoch 2550/5000 - Loss: 0.2469
Epoch 2560/5000 - Loss: 0.2469
Epoch 2570/5000 - Loss: 0.2467
Epoch 2580/5000 - Loss: 0.2464
Epoch 2590/5000 - Loss: 0.2462
Epoch 2600/5000 - Loss: 0.2462
Epoch 2610/5000 - Loss: 0.2462
Epoch 2620/5000 - Loss: 0.2462
Epoch 2630/5000 - Loss: 0.2463
Epoch 2640/5000 - Loss: 0.2462
Epoch 2650/5000 - Loss: 0.2460
Epoch 2660/5000 - Loss: 0.2460
Epoch 2670/5000 - Loss: 0.2460
Epoch 2680/5000 - Loss: 0.2458
Epoch 2690/5000 - Loss: 0.2455
Epoch 2700/5000 - Loss: 0.2453
Epoch 2710/5000 - Loss: 0.2452
Epoch 2720/5000 - Loss: 0.2450
Epoch 2730/5000 - Loss: 0.2448
Epoch 2740/5000 - Loss: 0.2445
Epoch 2750/5000 - Loss: 0.2446
Epoch 2760/5000 - Loss: 0.2447
Epoch 2770/5000 - Loss: 0.2445
Epoch 2780/5000 - Loss: 0.2440
Epoch 2790/5000 - Loss: 0.2438
Epoch 2800/5000 - Loss: 0.2439
Epoch 2810/5000 - Loss: 0.2439
Epoch 2820/5000 - Loss: 0.2439
Epoch 2830/5000 - Loss: 0.2436
Epoch 2840/5000 - Loss: 0.2433
Epoch 2850/5000 - Loss: 0.2430
Epoch 2860/5000 - Loss: 0.2430
Epoch 2870/5000 - Loss: 0.2433
Epoch 2880/5000 - Loss: 0.2435
Epoch 2890/5000 - Loss: 0.2432
Epoch 2900/5000 - Loss: 0.2428
Epoch 2910/5000 - Loss: 0.2425
Epoch 2920/5000 - Loss: 0.2423
Epoch 2930/5000 - Loss: 0.2422
Epoch 2940/5000 - Loss: 0.2422
Epoch 2950/5000 - Loss: 0.2420
Epoch 2960/5000 - Loss: 0.2418
Epoch 2970/5000 - Loss: 0.2419
Epoch 2980/5000 - Loss: 0.2419
Epoch 2990/5000 - Loss: 0.2419
Epoch 3000/5000 - Loss: 0.2418
Epoch 3010/5000 - Loss: 0.2415
Epoch 3020/5000 - Loss: 0.2414
Epoch 3030/5000 - Loss: 0.2412
Epoch 3040/5000 - Loss: 0.2412
Epoch 3050/5000 - Loss: 0.2412
Epoch 3060/5000 - Loss: 0.2410
Epoch 3070/5000 - Loss: 0.2409
Epoch 3080/5000 - Loss: 0.2407
Epoch 3090/5000 - Loss: 0.2406
Epoch 3100/5000 - Loss: 0.2403
Epoch 3110/5000 - Loss: 0.2400
Epoch 3120/5000 - Loss: 0.2399
Epoch 3130/5000 - Loss: 0.2399
Epoch 3140/5000 - Loss: 0.2400
Epoch 3150/5000 - Loss: 0.2399
Epoch 3160/5000 - Loss: 0.2397
Epoch 3170/5000 - Loss: 0.2395
Epoch 3180/5000 - Loss: 0.2393
Epoch 3190/5000 - Loss: 0.2393
Epoch 3200/5000 - Loss: 0.2392
Epoch 3210/5000 - Loss: 0.2392
Epoch 3220/5000 - Loss: 0.2390
Epoch 3230/5000 - Loss: 0.2387
Epoch 3240/5000 - Loss: 0.2386
Epoch 3250/5000 - Loss: 0.2386
Epoch 3260/5000 - Loss: 0.2386
Epoch 3270/5000 - Loss: 0.2385
Epoch 3280/5000 - Loss: 0.2383
Epoch 3290/5000 - Loss: 0.2382
Epoch 3300/5000 - Loss: 0.2384
Epoch 3310/5000 - Loss: 0.2385
Epoch 3320/5000 - Loss: 0.2385
Epoch 3330/5000 - Loss: 0.2382
Epoch 3340/5000 - Loss: 0.2378
Epoch 3350/5000 - Loss: 0.2375
Epoch 3360/5000 - Loss: 0.2376
Epoch 3370/5000 - Loss: 0.2377
Epoch 3380/5000 - Loss: 0.2376
Epoch 3390/5000 - Loss: 0.2372
Epoch 3400/5000 - Loss: 0.2369
Epoch 3410/5000 - Loss: 0.2369
Epoch 3420/5000 - Loss: 0.2371
Epoch 3430/5000 - Loss: 0.2372
Epoch 3440/5000 - Loss: 0.2368
Epoch 3450/5000 - Loss: 0.2364
Epoch 3460/5000 - Loss: 0.2364
Epoch 3470/5000 - Loss: 0.2366
Epoch 3480/5000 - Loss: 0.2365
Epoch 3490/5000 - Loss: 0.2362
Epoch 3500/5000 - Loss: 0.2361
Epoch 3510/5000 - Loss: 0.2362
Epoch 3520/5000 - Loss: 0.2362
Epoch 3530/5000 - Loss: 0.2362
Epoch 3540/5000 - Loss: 0.2360
Epoch 3550/5000 - Loss: 0.2358
Epoch 3560/5000 - Loss: 0.2355
Epoch 3570/5000 - Loss: 0.2353
Epoch 3580/5000 - Loss: 0.2353
Epoch 3590/5000 - Loss: 0.2355
Epoch 3600/5000 - Loss: 0.2355
Epoch 3610/5000 - Loss: 0.2352
Epoch 3620/5000 - Loss: 0.2348
Epoch 3630/5000 - Loss: 0.2346
Epoch 3640/5000 - Loss: 0.2349
Epoch 3650/5000 - Loss: 0.2353
Epoch 3660/5000 - Loss: 0.2352
Epoch 3670/5000 - Loss: 0.2347
Epoch 3680/5000 - Loss: 0.2344
Epoch 3690/5000 - Loss: 0.2344
Epoch 3700/5000 - Loss: 0.2347
Epoch 3710/5000 - Loss: 0.2349
Epoch 3720/5000 - Loss: 0.2346
Epoch 3730/5000 - Loss: 0.2342
Epoch 3740/5000 - Loss: 0.2338
Epoch 3750/5000 - Loss: 0.2336
Epoch 3760/5000 - Loss: 0.2336
Epoch 3770/5000 - Loss: 0.2337
Epoch 3780/5000 - Loss: 0.2338
Epoch 3790/5000 - Loss: 0.2338
Epoch 3800/5000 - Loss: 0.2336
Epoch 3810/5000 - Loss: 0.2331
Epoch 3820/5000 - Loss: 0.2328
Epoch 3830/5000 - Loss: 0.2329
Epoch 3840/5000 - Loss: 0.2331
Epoch 3850/5000 - Loss: 0.2333
Epoch 3860/5000 - Loss: 0.2332
Epoch 3870/5000 - Loss: 0.2328
Epoch 3880/5000 - Loss: 0.2325
Epoch 3890/5000 - Loss: 0.2325
Epoch 3900/5000 - Loss: 0.2326
Epoch 3910/5000 - Loss: 0.2325
Epoch 3920/5000 - Loss: 0.2324
Epoch 3930/5000 - Loss: 0.2323
Epoch 3940/5000 - Loss: 0.2322
Epoch 3950/5000 - Loss: 0.2321
Epoch 3960/5000 - Loss: 0.2321
Epoch 3970/5000 - Loss: 0.2321
Epoch 3980/5000 - Loss: 0.2320
Epoch 3990/5000 - Loss: 0.2316
Epoch 4000/5000 - Loss: 0.2315
Epoch 4010/5000 - Loss: 0.2315
Epoch 4020/5000 - Loss: 0.2315
Epoch 4030/5000 - Loss: 0.2314
Epoch 4040/5000 - Loss: 0.2312
Epoch 4050/5000 - Loss: 0.2312
Epoch 4060/5000 - Loss: 0.2310
Epoch 4070/5000 - Loss: 0.2309
Epoch 4080/5000 - Loss: 0.2309
Epoch 4090/5000 - Loss: 0.2308
Epoch 4100/5000 - Loss: 0.2307
Epoch 4110/5000 - Loss: 0.2309
Epoch 4120/5000 - Loss: 0.2310
Epoch 4130/5000 - Loss: 0.2309
Epoch 4140/5000 - Loss: 0.2307
Epoch 4150/5000 - Loss: 0.2303
Epoch 4160/5000 - Loss: 0.2301
Epoch 4170/5000 - Loss: 0.2303
Epoch 4180/5000 - Loss: 0.2305
Epoch 4190/5000 - Loss: 0.2304
Epoch 4200/5000 - Loss: 0.2302
Epoch 4210/5000 - Loss: 0.2299
Epoch 4220/5000 - Loss: 0.2298
Epoch 4230/5000 - Loss: 0.2300
Epoch 4240/5000 - Loss: 0.2300
Epoch 4250/5000 - Loss: 0.2296
Epoch 4260/5000 - Loss: 0.2297
Epoch 4270/5000 - Loss: 0.2298
Epoch 4280/5000 - Loss: 0.2296
Epoch 4290/5000 - Loss: 0.2295
Epoch 4300/5000 - Loss: 0.2295
Epoch 4310/5000 - Loss: 0.2296
Epoch 4320/5000 - Loss: 0.2294
Epoch 4330/5000 - Loss: 0.2293
Epoch 4340/5000 - Loss: 0.2293
Epoch 4350/5000 - Loss: 0.2292
Epoch 4360/5000 - Loss: 0.2291
Epoch 4370/5000 - Loss: 0.2289
Epoch 4380/5000 - Loss: 0.2288
Epoch 4390/5000 - Loss: 0.2288
Epoch 4400/5000 - Loss: 0.2288
Epoch 4410/5000 - Loss: 0.2286
Epoch 4420/5000 - Loss: 0.2282
Epoch 4430/5000 - Loss: 0.2282
Epoch 4440/5000 - Loss: 0.2284
Epoch 4450/5000 - Loss: 0.2284
Epoch 4460/5000 - Loss: 0.2282
Epoch 4470/5000 - Loss: 0.2280
Epoch 4480/5000 - Loss: 0.2278
Epoch 4490/5000 - Loss: 0.2280
Epoch 4500/5000 - Loss: 0.2283
Epoch 4510/5000 - Loss: 0.2283
Epoch 4520/5000 - Loss: 0.2276
Epoch 4530/5000 - Loss: 0.2273
Epoch 4540/5000 - Loss: 0.2273
Epoch 4550/5000 - Loss: 0.2274
Epoch 4560/5000 - Loss: 0.2275
Epoch 4570/5000 - Loss: 0.2275
Epoch 4580/5000 - Loss: 0.2272
Epoch 4590/5000 - Loss: 0.2269
Epoch 4600/5000 - Loss: 0.2267
Epoch 4610/5000 - Loss: 0.2268
Epoch 4620/5000 - Loss: 0.2271
Epoch 4630/5000 - Loss: 0.2270
Epoch 4640/5000 - Loss: 0.2265
Epoch 4650/5000 - Loss: 0.2263
Epoch 4660/5000 - Loss: 0.2263
Epoch 4670/5000 - Loss: 0.2264
Epoch 4680/5000 - Loss: 0.2266
Epoch 4690/5000 - Loss: 0.2266
Epoch 4700/5000 - Loss: 0.2263
Epoch 4710/5000 - Loss: 0.2260
Epoch 4720/5000 - Loss: 0.2258
Epoch 4730/5000 - Loss: 0.2257
Epoch 4740/5000 - Loss: 0.2259
Epoch 4750/5000 - Loss: 0.2258
Epoch 4760/5000 - Loss: 0.2258
Epoch 4770/5000 - Loss: 0.2258
Epoch 4780/5000 - Loss: 0.2258
Epoch 4790/5000 - Loss: 0.2257
Epoch 4800/5000 - Loss: 0.2255
Epoch 4810/5000 - Loss: 0.2253
Epoch 4820/5000 - Loss: 0.2251
Epoch 4830/5000 - Loss: 0.2251
Epoch 4840/5000 - Loss: 0.2256
Epoch 4850/5000 - Loss: 0.2258
Epoch 4860/5000 - Loss: 0.2254
Epoch 4870/5000 - Loss: 0.2248
Epoch 4880/5000 - Loss: 0.2246
Epoch 4890/5000 - Loss: 0.2247
Epoch 4900/5000 - Loss: 0.2251
Epoch 4910/5000 - Loss: 0.2251
Epoch 4920/5000 - Loss: 0.2245
Epoch 4930/5000 - Loss: 0.2242
Epoch 4940/5000 - Loss: 0.2242
Epoch 4950/5000 - Loss: 0.2245
Epoch 4960/5000 - Loss: 0.2246
Epoch 4970/5000 - Loss: 0.2243
Epoch 4980/5000 - Loss: 0.2238
Epoch 4990/5000 - Loss: 0.2238

In [111]:
# 1. Dự đoán trên tập test (đang ở dạng chuẩn hóa)
y_pred_scaled = mlp.predict(X_test_scaled)

# 2. Chuyển đổi ngược về đơn vị USD thực tế
y_pred = scaler_y.inverse_transform(y_pred_scaled)
y_test_real = y_test.reshape(-1, 1)

# 3. Tính toán các chỉ số bằng NumPy
mse_real = np.mean((y_pred - y_test_real) ** 2)
rmse_real = np.sqrt(mse_real)
mae_real = np.mean(np.abs(y_pred - y_test_real))

# 4. In kết quả
print("--- Kết quả đánh giá mô hình ---")
print(f"RMSE thực tế: ${rmse_real:,.2f} USD")
print(f"MAE thực tế : ${mae_real:,.2f} USD")

--- Kết quả đánh giá mô hình ---
RMSE thực tế: $56,963.08 USD
MAE thực tế : $37,795.94 USD